package com.traintracker

/**
 * Official Darwin delay (lateness) and cancellation reason codes.
 * Source: Network Rail Darwin reason code register.
 *
 * Cancel and delay use the same numeric codes but different wording, so they
 * are stored in separate maps. Use [resolveCancel] for cancelReason fields and
 * [resolveDelay] for delayReason fields.
 *
 * If the raw value is already human-readable text (non-numeric) it is returned unchanged.
 */
object DarwinReasonCodes {

    fun resolveCancel(raw: String): String = resolve(raw, cancelReasons)
    fun resolveDelay(raw: String):  String = resolve(raw, delayReasons)

    private fun resolve(raw: String, map: Map<Int, String>): String {
        if (raw.isEmpty()) return ""
        val n = raw.trim().toIntOrNull() ?: return raw
        return map[n] ?: "Reason code $n"
    }

    // ── Cancellation reasons ──────────────────────────────────────────────────

    private val cancelReasons: Map<Int, String> = mapOf(
        100 to "This train has been cancelled because of a broken down train",
        101 to "This train has been cancelled because of a delay on a previous journey",
        102 to "This train has been cancelled because of a derailed train",
        104 to "This train has been cancelled because of a fire at a station",
        105 to "This train has been cancelled because of a fire at a station earlier",
        106 to "This train has been cancelled because of a landslip",
        107 to "This train has been cancelled because of a line-side fire",
        108 to "This train has been cancelled because of a member of train crew being unavailable",
        109 to "This train has been cancelled because of a passenger being taken ill",
        110 to "This train has been cancelled because of a passenger having been taken ill earlier",
        111 to "This train has been cancelled because of a person hit by a train",
        112 to "This train has been cancelled because of a person hit by a train earlier",
        113 to "This train has been cancelled because of a problem at a level crossing",
        114 to "This train has been cancelled because of a problem currently under investigation",
        115 to "This train has been cancelled because of a problem near the railway",
        116 to "This train has been cancelled because of a problem with a river bridge",
        117 to "This train has been cancelled because of a problem with line side equipment",
        118 to "This train has been cancelled because of a security alert",
        119 to "This train has been cancelled because of a train derailed earlier",
        120 to "This train has been cancelled because of a train fault",
        121 to "This train has been cancelled because of a train late from the depot",
        122 to "This train has been cancelled because of a train late from the depot earlier",
        123 to "This train has been cancelled because of a trespass incident",
        124 to "This train has been cancelled because of a vehicle striking a bridge",
        125 to "This train has been cancelled because of a vehicle striking a bridge earlier",
        126 to "This train has been cancelled because of an earlier broken down train",
        128 to "This train has been cancelled because of an earlier landslip",
        129 to "This train has been cancelled because of an earlier line-side fire",
        130 to "This train has been cancelled because of an earlier operating incident",
        131 to "This train has been cancelled because of an earlier problem at a level crossing",
        132 to "This train has been cancelled because of an earlier problem near the railway",
        133 to "This train has been cancelled because of an earlier problem with a river bridge",
        134 to "This train has been cancelled because of an earlier problem with line side equipment",
        135 to "This train has been cancelled because of an earlier security alert",
        136 to "This train has been cancelled because of an earlier train fault",
        137 to "This train has been cancelled because of an earlier trespass incident",
        138 to "This train has been cancelled because of an obstruction on the line",
        139 to "This train has been cancelled because of an obstruction on the line earlier",
        140 to "This train has been cancelled because of an operating incident",
        141 to "This train has been cancelled because of an unusually large passenger flow",
        142 to "This train has been cancelled because of an unusually large passenger flow earlier",
        143 to "This train has been cancelled because of animals on the line",
        144 to "This train has been cancelled because of animals on the line earlier",
        145 to "This train has been cancelled because of congestion caused by earlier delays",
        146 to "This train has been cancelled because of disruptive passengers",
        147 to "This train has been cancelled because of disruptive passengers earlier",
        148 to "This train has been cancelled because of earlier electrical supply problems",
        149 to "This train has been cancelled because of earlier emergency engineering works",
        150 to "This train has been cancelled because of earlier industrial action",
        151 to "This train has been cancelled because of earlier overhead wire problems",
        152 to "This train has been cancelled because of earlier over-running engineering works",
        153 to "This train has been cancelled because of earlier signalling problems",
        154 to "This train has been cancelled because of earlier vandalism",
        155 to "This train has been cancelled because of electrical supply problems",
        156 to "This train has been cancelled because of emergency engineering works",
        157 to "This train has been cancelled because of emergency services dealing with a prior incident",
        158 to "This train has been cancelled because of emergency services dealing with an incident",
        159 to "This train has been cancelled because of fire alarms sounding at a station",
        160 to "This train has been cancelled because of fire alarms sounding earlier at a station",
        161 to "This train has been cancelled because of flooding",
        162 to "This train has been cancelled because of flooding earlier",
        163 to "This train has been cancelled because of fog",
        164 to "This train has been cancelled because of fog earlier",
        165 to "This train has been cancelled because of high winds",
        166 to "This train has been cancelled because of high winds earlier",
        167 to "This train has been cancelled because of industrial action",
        168 to "This train has been cancelled because of lightning having damaged equipment",
        169 to "This train has been cancelled because of overhead wire problems",
        170 to "This train has been cancelled because of over-running engineering works",
        171 to "This train has been cancelled because of passengers transferring between trains",
        172 to "This train has been cancelled because of passengers transferring between trains earlier",
        173 to "This train has been cancelled because of poor rail conditions",
        174 to "This train has been cancelled because of poor rail conditions earlier",
        175 to "This train has been cancelled because of poor weather conditions",
        176 to "This train has been cancelled because of poor weather conditions earlier",
        177 to "This train has been cancelled because of safety checks being made",
        178 to "This train has been cancelled because of safety checks having been made earlier",
        179 to "This train has been cancelled because of signalling problems",
        180 to "This train has been cancelled because of snow",
        181 to "This train has been cancelled because of snow earlier",
        182 to "This train has been cancelled because of speed restrictions having been imposed",
        183 to "This train has been cancelled because of train crew having been unavailable earlier",
        184 to "This train has been cancelled because of vandalism",
        185 to "This train has been cancelled because of waiting earlier for a train crew member",
        186 to "This train has been cancelled because of waiting for a train crew member",
        187 to "This train has been cancelled because of engineering works",
        501 to "This train has been cancelled because of a broken down train",
        502 to "This train has been cancelled because of a broken windscreen on the train",
        503 to "This train has been cancelled because of a shortage of trains because of accident damage",
        504 to "This train has been cancelled because of a shortage of trains because of extra safety inspections",
        505 to "This train has been cancelled because of a shortage of trains because of vandalism",
        506 to "This train has been cancelled because of a shortage of trains following damage by snow and ice",
        507 to "This train has been cancelled because of more trains than usual needing repairs at the same time",
        508 to "This train has been cancelled because of the train for this service having broken down",
        509 to "This train has been cancelled because of this train breaking down",
        510 to "This train has been cancelled because of a collision between trains",
        511 to "This train has been cancelled because of a collision with the buffers at a station",
        512 to "This train has been cancelled because of a derailed train",
        513 to "This train has been cancelled because of a derailment within the depot",
        514 to "This train has been cancelled because of a low speed derailment",
        515 to "This train has been cancelled because of a train being involved in an accident",
        516 to "This train has been cancelled because of trains being involved in an accident",
        517 to "This train has been cancelled because of a fire at a station",
        518 to "This train has been cancelled because of a fire at a station earlier today",
        519 to "This train has been cancelled because of a landslip",
        520 to "This train has been cancelled because of a fire next to the track",
        521 to "This train has been cancelled because of a fire on a train",
        522 to "This train has been cancelled because of a member of on train staff being taken ill",
        523 to "This train has been cancelled because of a shortage of on train staff",
        524 to "This train has been cancelled because of a shortage of train conductors",
        525 to "This train has been cancelled because of a shortage of train crew",
        526 to "This train has been cancelled because of a shortage of train drivers",
        527 to "This train has been cancelled because of a shortage of train guards",
        528 to "This train has been cancelled because of a shortage of train managers",
        529 to "This train has been cancelled because of severe weather preventing train crew getting to work",
        530 to "This train has been cancelled because of the train conductor being taken ill",
        531 to "This train has been cancelled because of the train driver being taken ill",
        532 to "This train has been cancelled because of the train guard being taken ill",
        533 to "This train has been cancelled because of the train manager being taken ill",
        534 to "This train has been cancelled because of a passenger being taken ill at a station",
        535 to "This train has been cancelled because of a passenger being taken ill on a train",
        536 to "This train has been cancelled because of a passenger being taken ill on this train",
        537 to "This train has been cancelled because of a passenger being taken ill at a station earlier today",
        538 to "This train has been cancelled because of a passenger being taken ill on a train earlier today",
        539 to "This train has been cancelled because of a passenger being taken ill on this train earlier in its journey",
        540 to "This train has been cancelled because of a person being hit by a train",
        541 to "This train has been cancelled because of a person being hit by a train earlier today",
        542 to "This train has been cancelled because of a collision at a level crossing",
        543 to "This train has been cancelled because of a fault with barriers at a level crossing",
        544 to "This train has been cancelled because of a road accident at a level crossing",
        545 to "This train has been cancelled because of a road vehicle colliding with level crossing barriers",
        546 to "This train has been cancelled because of a road vehicle damaging track at a level crossing",
        547 to "This train has been cancelled because of a problem currently under investigation",
        548 to "This train has been cancelled because of a burst water main near the railway",
        549 to "This train has been cancelled because of a chemical spillage near the railway",
        550 to "This train has been cancelled because of a fire near the railway involving gas cylinders",
        551 to "This train has been cancelled because of a fire near the railway suspected to involve gas cylinders",
        552 to "This train has been cancelled because of a fire on property near the railway",
        553 to "This train has been cancelled because of a gas leak near the railway",
        554 to "This train has been cancelled because of a road accident near the railway",
        555 to "This train has been cancelled because of a wartime bomb near the railway",
        556 to "This train has been cancelled because of ambulance service dealing with an incident near the railway",
        557 to "This train has been cancelled because of emergency services dealing with an incident near the railway",
        558 to "This train has been cancelled because of fire brigade dealing with an incident near the railway",
        559 to "This train has been cancelled because of police dealing with an incident near the railway",
        560 to "This train has been cancelled because of a boat colliding with a bridge",
        561 to "This train has been cancelled because of a fault with a swing bridge over a river",
        562 to "This train has been cancelled because of a problem with a river bridge",
        563 to "This train has been cancelled because of a problem with line-side equipment",
        564 to "This train has been cancelled because of a security alert at a station",
        565 to "This train has been cancelled because of a security alert on another train",
        566 to "This train has been cancelled because of a security alert on this train",
        567 to "This train has been cancelled because of a train derailment earlier today",
        568 to "This train has been cancelled because of a train derailment yesterday",
        569 to "This train has been cancelled because of a fault occurring when attaching a part of a train",
        570 to "This train has been cancelled because of a fault occurring when attaching a part of this train",
        571 to "This train has been cancelled because of a fault occurring when detaching a part of a train",
        572 to "This train has been cancelled because of a fault occurring when detaching a part of this train",
        573 to "This train has been cancelled because of a fault on a train in front of this one",
        574 to "This train has been cancelled because of a fault on this train",
        575 to "This train has been cancelled because of this train being late from the depot",
        576 to "This train has been cancelled because of trespassers on the railway",
        577 to "This train has been cancelled because of a bus colliding with a bridge",
        578 to "This train has been cancelled because of a lorry colliding with a bridge",
        579 to "This train has been cancelled because of a road vehicle colliding with a bridge",
        580 to "This train has been cancelled because of a bus colliding with a bridge earlier on this train's journey",
        581 to "This train has been cancelled because of a bus colliding with a bridge earlier today",
        582 to "This train has been cancelled because of a lorry colliding with a bridge earlier on this train's journey",
        583 to "This train has been cancelled because of a lorry colliding with a bridge earlier today",
        584 to "This train has been cancelled because of a road vehicle colliding with a bridge earlier on this train's journey",
        585 to "This train has been cancelled because of a road vehicle colliding with a bridge earlier today",
        586 to "This train has been cancelled because of a broken down train earlier today",
        587 to "This train has been cancelled because of an earlier landslip",
        588 to "This train has been cancelled because of a fire next to the track earlier today",
        589 to "This train has been cancelled because of a fire on a train earlier today",
        590 to "This train has been cancelled because of a coach becoming uncoupled on a train earlier in its journey",
        591 to "This train has been cancelled because of a coach becoming uncoupled on a train earlier today",
        592 to "This train has been cancelled because of a coach becoming uncoupled on this train earlier in its journey",
        593 to "This train has been cancelled because of a coach becoming uncoupled on this train earlier today",
        594 to "This train has been cancelled because of a train not stopping at a station it was supposed to earlier in its journey",
        595 to "This train has been cancelled because of a train not stopping at a station it was supposed to earlier today",
        596 to "This train has been cancelled because of a train not stopping in the correct position at a station earlier in its journey",
        597 to "This train has been cancelled because of a train not stopping in the correct position at a station earlier today",
        598 to "This train has been cancelled because of a train's automatic braking system being activated earlier in its journey",
        599 to "This train has been cancelled because of a train's automatic braking system being activated earlier today",
        600 to "This train has been cancelled because of an operational incident earlier in its journey",
        601 to "This train has been cancelled because of an operational incident earlier today",
        602 to "This train has been cancelled because of this train not stopping at a station it was supposed to earlier in its journey",
        603 to "This train has been cancelled because of this train not stopping at a station it was supposed to earlier today",
        604 to "This train has been cancelled because of this train not stopping in the correct position at a station earlier in its journey",
        605 to "This train has been cancelled because of this train not stopping in the correct position at a station earlier today",
        606 to "This train has been cancelled because of this train's automatic braking system being activated earlier in its journey",
        607 to "This train has been cancelled because of this train's automatic braking system being activated earlier today",
        608 to "This train has been cancelled because of a collision at a level crossing earlier today",
        609 to "This train has been cancelled because of a collision at a level crossing yesterday",
        610 to "This train has been cancelled because of a fault with barriers at a level crossing earlier today",
        611 to "This train has been cancelled because of a fault with barriers at a level crossing yesterday",
        612 to "This train has been cancelled because of a road accident at a level crossing earlier today",
        613 to "This train has been cancelled because of a road accident at a level crossing yesterday",
        614 to "This train has been cancelled because of a road vehicle colliding with level crossing barriers earlier today",
        615 to "This train has been cancelled because of a road vehicle colliding with level crossing barriers yesterday",
        616 to "This train has been cancelled because of a road vehicle damaging track at a level crossing earlier today",
        617 to "This train has been cancelled because of a road vehicle damaging track at a level crossing yesterday",
        618 to "This train has been cancelled because of a burst water main near the railway earlier today",
        619 to "This train has been cancelled because of a burst water main near the railway yesterday",
        620 to "This train has been cancelled because of a chemical spillage near the railway earlier today",
        621 to "This train has been cancelled because of a chemical spillage near the railway yesterday",
        622 to "This train has been cancelled because of a fire near the railway involving gas cylinders earlier today",
        623 to "This train has been cancelled because of a fire near the railway involving gas cylinders yesterday",
        624 to "This train has been cancelled because of a fire near the railway suspected to involve gas cylinders earlier today",
        625 to "This train has been cancelled because of a fire near the railway suspected to involve gas cylinders yesterday",
        626 to "This train has been cancelled because of a fire on property near the railway earlier today",
        627 to "This train has been cancelled because of a fire on property near the railway yesterday",
        628 to "This train has been cancelled because of a gas leak near the railway earlier today",
        629 to "This train has been cancelled because of a gas leak near the railway yesterday",
        630 to "This train has been cancelled because of a road accident near the railway earlier today",
        631 to "This train has been cancelled because of a road accident near the railway yesterday",
        632 to "This train has been cancelled because of a wartime bomb near the railway earlier today",
        633 to "This train has been cancelled because of a wartime bomb near the railway yesterday",
        634 to "This train has been cancelled because of a wartime bomb which has now been made safe",
        635 to "This train has been cancelled because of ambulance service dealing with an incident near the railway earlier today",
        636 to "This train has been cancelled because of ambulance service dealing with an incident near the railway yesterday",
        637 to "This train has been cancelled because of emergency services dealing with an incident near the railway earlier today",
        638 to "This train has been cancelled because of emergency services dealing with an incident near the railway yesterday",
        639 to "This train has been cancelled because of fire brigade dealing with an incident near the railway earlier today",
        640 to "This train has been cancelled because of fire brigade dealing with an incident near the railway yesterday",
        641 to "This train has been cancelled because of police dealing with an incident near the railway earlier today",
        642 to "This train has been cancelled because of police dealing with an incident near the railway yesterday",
        643 to "This train has been cancelled because of a boat colliding with a bridge earlier today",
        644 to "This train has been cancelled because of a fault with a swing bridge over a river earlier today",
        645 to "This train has been cancelled because of a problem with a river bridge earlier today",
        646 to "This train has been cancelled because of an earlier problem with line-side equipment",
        647 to "This train has been cancelled because of a security alert earlier today",
        648 to "This train has been cancelled because of a fault on this train which is now fixed",
        649 to "This train has been cancelled because of trespassers on the railway earlier in this train's journey",
        650 to "This train has been cancelled because of trespassers on the railway earlier today",
        651 to "This train has been cancelled because of a bicycle on the track",
        652 to "This train has been cancelled because of a road vehicle blocking the railway",
        653 to "This train has been cancelled because of a supermarket trolley on the track",
        654 to "This train has been cancelled because of a train hitting an obstruction on the line",
        655 to "This train has been cancelled because of a tree blocking the railway",
        656 to "This train has been cancelled because of an obstruction on the track",
        657 to "This train has been cancelled because of checking reports of an obstruction on the line",
        658 to "This train has been cancelled because of this train hitting an obstruction on the line",
        659 to "This train has been cancelled because of a bicycle on the track earlier on this train's journey",
        660 to "This train has been cancelled because of a bicycle on the track earlier today",
        661 to "This train has been cancelled because of a road vehicle blocking the railway earlier on this train's journey",
        662 to "This train has been cancelled because of a road vehicle blocking the railway earlier today",
        663 to "This train has been cancelled because of a supermarket trolley on the track earlier on this train's journey",
        664 to "This train has been cancelled because of a supermarket trolley on the track earlier today",
        665 to "This train has been cancelled because of a train hitting an obstruction on the line earlier on this train's journey",
        666 to "This train has been cancelled because of a train hitting an obstruction on the line earlier today",
        667 to "This train has been cancelled because of a tree blocking the railway earlier on this train's journey",
        668 to "This train has been cancelled because of a tree blocking the railway earlier today",
        669 to "This train has been cancelled because of an obstruction on the track earlier on this train's journey",
        670 to "This train has been cancelled because of an obstruction on the track earlier today",
        671 to "This train has been cancelled because of checking reports of an obstruction on the line earlier on this train's journey",
        672 to "This train has been cancelled because of checking reports of an obstruction on the line earlier today",
        673 to "This train has been cancelled because of this train hitting an obstruction on the line earlier in its journey",
        674 to "This train has been cancelled because of this train hitting an obstruction on the line earlier on this train's journey",
        675 to "This train has been cancelled because of this train hitting an obstruction on the line earlier today",
        676 to "This train has been cancelled because of a coach becoming uncoupled on a train",
        677 to "This train has been cancelled because of a coach becoming uncoupled on this train",
        678 to "This train has been cancelled because of a train not stopping at a station it was supposed to",
        679 to "This train has been cancelled because of a train not stopping in the correct position at a station",
        680 to "This train has been cancelled because of a train's automatic braking system being activated",
        681 to "This train has been cancelled because of an operational incident",
        682 to "This train has been cancelled because of this train not stopping at a station it was supposed to",
        683 to "This train has been cancelled because of this train not stopping in the correct position at a station",
        684 to "This train has been cancelled because of this train's automatic braking system being activated",
        685 to "This train has been cancelled because of overcrowding",
        686 to "This train has been cancelled because of overcrowding as this train has fewer coaches than normal",
        687 to "This train has been cancelled because of overcrowding because an earlier train had fewer coaches than normal",
        688 to "This train has been cancelled because of overcrowding because of a concert",
        689 to "This train has been cancelled because of overcrowding because of a football match",
        690 to "This train has been cancelled because of overcrowding because of a marathon",
        691 to "This train has been cancelled because of overcrowding because of a rugby match",
        692 to "This train has been cancelled because of overcrowding because of a sporting event",
        693 to "This train has been cancelled because of overcrowding because of an earlier cancellation",
        694 to "This train has been cancelled because of overcrowding because of an event",
        695 to "This train has been cancelled because of overcrowding earlier on this train's journey",
        696 to "This train has been cancelled because of animals on the railway",
        697 to "This train has been cancelled because of cattle on the railway",
        698 to "This train has been cancelled because of horses on the railway",
        699 to "This train has been cancelled because of sheep on the railway",
        700 to "This train has been cancelled because of animals on the railway earlier today",
        701 to "This train has been cancelled because of cattle on the railway earlier today",
        702 to "This train has been cancelled because of horses on the railway earlier today",
        703 to "This train has been cancelled because of sheep on the railway earlier today",
        704 to "This train has been cancelled because of passengers causing a disturbance on a train",
        705 to "This train has been cancelled because of passengers causing a disturbance on this train",
        706 to "This train has been cancelled because of passengers causing a disturbance earlier in this train's journey",
        707 to "This train has been cancelled because of passengers causing a disturbance on a train earlier today",
        708 to "This train has been cancelled because of a fault with the electric third rail earlier on this train's journey",
        709 to "This train has been cancelled because of a fault with the electric third rail earlier today",
        710 to "This train has been cancelled because of damage to the electric third rail earlier on this train's journey",
        711 to "This train has been cancelled because of damage to the electric third rail earlier today",
        712 to "This train has been cancelled because of failure of the electricity supply earlier on this train's journey",
        713 to "This train has been cancelled because of failure of the electricity supply earlier today",
        714 to "This train has been cancelled because of the electricity being switched off for safety reasons earlier on this train's journey",
        715 to "This train has been cancelled because of the electricity being switched off for safety reasons earlier today",
        716 to "This train has been cancelled because of urgent repairs to a bridge earlier today",
        717 to "This train has been cancelled because of urgent repairs to a tunnel earlier today",
        718 to "This train has been cancelled because of urgent repairs to the railway earlier today",
        719 to "This train has been cancelled because of urgent repairs to the track earlier today",
        720 to "This train has been cancelled because of expected industrial action earlier today",
        721 to "This train has been cancelled because of expected industrial action yesterday",
        722 to "This train has been cancelled because of industrial action earlier today",
        723 to "This train has been cancelled because of industrial action yesterday",
        724 to "This train has been cancelled because of an object being caught on the overhead electric wires earlier on this train's journey",
        725 to "This train has been cancelled because of an object being caught on the overhead electric wires earlier today",
        726 to "This train has been cancelled because of damage to the overhead electric wires earlier on this train's journey",
        727 to "This train has been cancelled because of damage to the overhead electric wires earlier today",
        728 to "This train has been cancelled because of earlier engineering works not being finished on time",
        729 to "This train has been cancelled because of a fault with the on train signalling system earlier on this train's journey",
        730 to "This train has been cancelled because of a fault with the on train signalling system earlier today",
        731 to "This train has been cancelled because of a fault with the radio system between the driver and the signaller earlier on this train's journey",
        732 to "This train has been cancelled because of a fault with the radio system between the driver and the signaller earlier today",
        733 to "This train has been cancelled because of a fault with the signalling system earlier on this train's journey",
        734 to "This train has been cancelled because of a fault with the signalling system earlier today",
        735 to "This train has been cancelled because of signalling staff being taken ill earlier on this train's journey",
        736 to "This train has been cancelled because of signalling staff being taken ill earlier today",
        737 to "This train has been cancelled because of the fire alarm sounding in a signalbox earlier on this train's journey",
        738 to "This train has been cancelled because of the fire alarm sounding in a signalbox earlier today",
        739 to "This train has been cancelled because of the fire alarm sounding in the signalling centre earlier on this train's journey",
        740 to "This train has been cancelled because of the fire alarm sounding in the signalling centre earlier today",
        741 to "This train has been cancelled because of attempted theft of overhead line electrification equipment earlier today",
        742 to "This train has been cancelled because of attempted theft of overhead line electrification equipment yesterday",
        743 to "This train has been cancelled because of attempted theft of railway equipment earlier today",
        744 to "This train has been cancelled because of attempted theft of railway equipment yesterday",
        745 to "This train has been cancelled because of attempted theft of signalling cables earlier today",
        746 to "This train has been cancelled because of attempted theft of signalling cables yesterday",
        747 to "This train has been cancelled because of attempted theft of third rail electrification equipment earlier today",
        748 to "This train has been cancelled because of attempted theft of third rail electrification equipment yesterday",
        749 to "This train has been cancelled because of theft of overhead line electrification equipment earlier today",
        750 to "This train has been cancelled because of theft of overhead line electrification equipment yesterday",
        751 to "This train has been cancelled because of theft of railway equipment earlier today",
        752 to "This train has been cancelled because of theft of railway equipment yesterday",
        753 to "This train has been cancelled because of theft of signalling cables earlier today",
        754 to "This train has been cancelled because of theft of signalling cables yesterday",
        755 to "This train has been cancelled because of theft of third rail electrification equipment earlier today",
        756 to "This train has been cancelled because of theft of third rail electrification equipment yesterday",
        757 to "This train has been cancelled because of vandalism at a station earlier today",
        758 to "This train has been cancelled because of vandalism at a station yesterday",
        759 to "This train has been cancelled because of vandalism of railway equipment earlier today",
        760 to "This train has been cancelled because of vandalism of railway equipment yesterday",
        761 to "This train has been cancelled because of vandalism on a train earlier today",
        762 to "This train has been cancelled because of vandalism on a train yesterday",
        763 to "This train has been cancelled because of vandalism on this train earlier today",
        764 to "This train has been cancelled because of vandalism on this train yesterday",
        765 to "This train has been cancelled because of a fault with the electric third rail",
        766 to "This train has been cancelled because of damage to the electric third rail",
        767 to "This train has been cancelled because of failure of the electricity supply",
        768 to "This train has been cancelled because of the electricity being switched off for safety reasons",
        769 to "This train has been cancelled because of urgent repairs to a bridge",
        770 to "This train has been cancelled because of urgent repairs to a tunnel",
        771 to "This train has been cancelled because of urgent repairs to the railway",
        772 to "This train has been cancelled because of urgent repairs to the track",
        773 to "This train has been cancelled because of the emergency services dealing with an incident earlier today",
        774 to "This train has been cancelled because of ambulance service dealing with an incident",
        775 to "This train has been cancelled because of fire brigade dealing with an incident",
        776 to "This train has been cancelled because of police dealing with an incident",
        777 to "This train has been cancelled because of the emergency services dealing with an incident",
        778 to "This train has been cancelled because of the fire alarm sounding at a station",
        779 to "This train has been cancelled because of the fire alarm sounding at a station earlier today",
        780 to "This train has been cancelled because of a burst water main flooding the railway",
        781 to "This train has been cancelled because of a river flooding the railway",
        782 to "This train has been cancelled because of flood water making the railway potentially unsafe",
        783 to "This train has been cancelled because of flooding",
        784 to "This train has been cancelled because of heavy rain flooding the railway",
        785 to "This train has been cancelled because of predicted flooding",
        786 to "This train has been cancelled because of the sea flooding the railway",
        787 to "This train has been cancelled because of a burst water main flooding the railway earlier today",
        788 to "This train has been cancelled because of a river flooding the railway earlier today",
        789 to "This train has been cancelled because of flood water making the railway potentially unsafe earlier today",
        790 to "This train has been cancelled because of flooding earlier in this train's journey",
        791 to "This train has been cancelled because of flooding earlier today",
        792 to "This train has been cancelled because of heavy rain flooding the railway earlier today",
        793 to "This train has been cancelled because of predicted flooding earlier today",
        794 to "This train has been cancelled because of the sea flooding the railway earlier today",
        795 to "This train has been cancelled because of thick fog",
        796 to "This train has been cancelled because of thick fog earlier in this train's journey",
        797 to "This train has been cancelled because of thick fog earlier today",
        798 to "This train has been cancelled because of forecasted high winds",
        799 to "This train has been cancelled because of high winds",
        800 to "This train has been cancelled because of high winds earlier in this train's journey",
        801 to "This train has been cancelled because of high winds earlier today",
        802 to "This train has been cancelled because of expected industrial action",
        803 to "This train has been cancelled because of industrial action",
        804 to "This train has been cancelled because of lightning damaging a station",
        805 to "This train has been cancelled because of lightning damaging a train",
        806 to "This train has been cancelled because of lightning damaging equipment",
        807 to "This train has been cancelled because of lightning damaging the electricity supply",
        808 to "This train has been cancelled because of lightning damaging the signalling system",
        809 to "This train has been cancelled because of lightning damaging this train",
        810 to "This train has been cancelled because of an object being caught on the overhead electric wires",
        811 to "This train has been cancelled because of damage to the overhead electric wires",
        812 to "This train has been cancelled because of engineering works not being finished on time",
        813 to "This train has been cancelled because of forecasted slippery rails",
        814 to "This train has been cancelled because of ice preventing this train getting electricity from the third rail",
        815 to "This train has been cancelled because of ice preventing trains getting electricity from the third rail",
        816 to "This train has been cancelled because of slippery rails",
        817 to "This train has been cancelled because of slippery rails earlier in this train's journey",
        818 to "This train has been cancelled because of slippery rails earlier today",
        819 to "This train has been cancelled because of forecasted severe weather",
        820 to "This train has been cancelled because of severe weather",
        821 to "This train has been cancelled because of severe weather earlier",
        822 to "This train has been cancelled because of severe weather earlier in this train's journey",
        823 to "This train has been cancelled because of severe weather earlier today",
        824 to "This train has been cancelled because of a safety inspection of the track",
        825 to "This train has been cancelled because of a safety inspection on a train",
        826 to "This train has been cancelled because of a safety inspection on this train",
        827 to "This train has been cancelled because of a safety inspection of the track earlier today",
        828 to "This train has been cancelled because of a safety inspection on a train earlier today",
        829 to "This train has been cancelled because of a safety inspection on this train earlier in its journey",
        830 to "This train has been cancelled because of a fault with the on train signalling system",
        831 to "This train has been cancelled because of a fault with the radio system between the driver and the signaller",
        832 to "This train has been cancelled because of a fault with the signalling system",
        833 to "This train has been cancelled because of signalling staff being taken ill",
        834 to "This train has been cancelled because of the fire alarm sounding in a signalbox",
        835 to "This train has been cancelled because of the fire alarm sounding in the signalling centre",
        836 to "This train has been cancelled because of forecasted heavy snow",
        837 to "This train has been cancelled because of heavy snow",
        838 to "This train has been cancelled because of heavy snow earlier in this train's journey",
        839 to "This train has been cancelled because of heavy snow earlier today",
        840 to "This train has been cancelled because of heavy snow over recent days",
        841 to "This train has been cancelled because of a speed restriction",
        842 to "This train has been cancelled because of a speed restriction because of fog",
        843 to "This train has been cancelled because of a speed restriction because of fog earlier on this train's journey",
        844 to "This train has been cancelled because of a speed restriction because of fog earlier today",
        845 to "This train has been cancelled because of a speed restriction because of heavy rain",
        846 to "This train has been cancelled because of a speed restriction because of heavy rain earlier on this train's journey",
        847 to "This train has been cancelled because of a speed restriction because of heavy rain earlier today",
        848 to "This train has been cancelled because of a speed restriction because of high track temperatures",
        849 to "This train has been cancelled because of a speed restriction because of high track temperatures earlier on this train's journey",
        850 to "This train has been cancelled because of a speed restriction because of high track temperatures earlier today",
        851 to "This train has been cancelled because of a speed restriction because of high winds",
        852 to "This train has been cancelled because of a speed restriction because of high winds earlier on this train's journey",
        853 to "This train has been cancelled because of a speed restriction because of high winds earlier today",
        854 to "This train has been cancelled because of a speed restriction because of severe weather",
        855 to "This train has been cancelled because of a speed restriction because of severe weather earlier on this train's journey",
        856 to "This train has been cancelled because of a speed restriction because of severe weather earlier today",
        857 to "This train has been cancelled because of a speed restriction because of snow and ice",
        858 to "This train has been cancelled because of a speed restriction because of snow and ice earlier on this train's journey",
        859 to "This train has been cancelled because of a speed restriction because of snow and ice earlier today",
        860 to "This train has been cancelled because of a speed restriction earlier on this train's journey",
        861 to "This train has been cancelled because of a speed restriction earlier today",
        862 to "This train has been cancelled because of a speed restriction in a tunnel",
        863 to "This train has been cancelled because of a speed restriction in a tunnel earlier on this train's journey",
        864 to "This train has been cancelled because of a speed restriction in a tunnel earlier today",
        865 to "This train has been cancelled because of a speed restriction over a bridge",
        866 to "This train has been cancelled because of a speed restriction over a bridge earlier on this train's journey",
        867 to "This train has been cancelled because of a speed restriction over a bridge earlier today",
        868 to "This train has been cancelled because of a speed restriction over an embankment",
        869 to "This train has been cancelled because of a speed restriction over an embankment earlier on this train's journey",
        870 to "This train has been cancelled because of a speed restriction over an embankment earlier today",
        871 to "This train has been cancelled because of a speed restriction over defective track",
        872 to "This train has been cancelled because of a speed restriction over defective track earlier on this train's journey",
        873 to "This train has been cancelled because of a speed restriction over defective track earlier today",
        874 to "This train has been cancelled because of attempted theft of overhead line electrification equipment",
        875 to "This train has been cancelled because of attempted theft of railway equipment",
        876 to "This train has been cancelled because of attempted theft of signalling cables",
        877 to "This train has been cancelled because of attempted theft of third rail electrification equipment",
        878 to "This train has been cancelled because of theft of overhead line electrification equipment",
        879 to "This train has been cancelled because of theft of railway equipment",
        880 to "This train has been cancelled because of theft of signalling cables",
        881 to "This train has been cancelled because of theft of third rail electrification equipment",
        882 to "This train has been cancelled because of vandalism at a station",
        883 to "This train has been cancelled because of vandalism of railway equipment",
        884 to "This train has been cancelled because of vandalism on a train",
        885 to "This train has been cancelled because of vandalism on this train",
        886 to "This train has been cancelled because of train crew being delayed",
        887 to "This train has been cancelled because of train crew being delayed by service disruption",
        888 to "This train has been cancelled because of a bridge being damaged",
        889 to "This train has been cancelled because of a bridge being damaged by a boat",
        890 to "This train has been cancelled because of a bridge being damaged by a road vehicle",
        891 to "This train has been cancelled because of a bridge having collapsed",
        892 to "This train has been cancelled because of a broken rail",
        893 to "This train has been cancelled because of a late departure while the train was cleaned specially",
        894 to "This train has been cancelled because of a late running freight train",
        895 to "This train has been cancelled because of a late running train being in front of this one",
        896 to "This train has been cancelled because of a points failure",
        897 to "This train has been cancelled because of a power cut at the station",
        898 to "This train has been cancelled because of a problem with the station lighting",
        899 to "This train has been cancelled because of a rail buckling in the heat",
        900 to "This train has been cancelled because of a railway embankment being damaged",
        901 to "This train has been cancelled because of a shortage of station staff",
        902 to "This train has been cancelled because of a tunnel being closed for safety reasons",
        903 to "This train has been cancelled because of an incident at the airport",
        904 to "This train has been cancelled because of congestion",
        905 to "This train has been cancelled because of the communication alarm being activated on a train",
        906 to "This train has been cancelled because of the communication alarm being activated on this train",
        907 to "This train has been cancelled because of the train departing late to maintain customer connections",
        908 to "This train has been cancelled because of the train making extra stops because a train was cancelled",
        909 to "This train has been cancelled because of the train making extra stops because of service disruption",
        910 to "This train has been cancelled because of waiting for a part of the train to be attached",
        911 to "This train has been cancelled because of a fault on a train",
        912 to "This train has been cancelled because of a problem with platform equipment",
        913 to "This train has been cancelled because of a fault on a train earlier",
        914 to "This train has been cancelled because of issues with communication systems",
        915 to "This train has been cancelled because of a problem in the depot",
        916 to "This train has been cancelled because of signalling staff being unavailable",
        917 to "This train has been cancelled because of staff training",
        918 to "This train has been cancelled because of a short-notice change to the timetable",
        919 to "This train has been cancelled because of misuse of a level crossing",
        920 to "This train has been cancelled because of a member of train crew being unavailable",
        921 to "This train has been cancelled because of a member of train crew being unavailable earlier"
    )

    // ── Lateness (delay) reasons ──────────────────────────────────────────────

    private val delayReasons: Map<Int, String> = mapOf(
        100 to "This train has been delayed by a broken down train",
        101 to "This train has been delayed by a delay on a previous journey",
        102 to "This train has been delayed by a derailed train",
        104 to "This train has been delayed by a fire at a station",
        105 to "This train has been delayed by a fire at a station earlier",
        106 to "This train has been delayed by a landslip",
        107 to "This train has been delayed by a line-side fire",
        108 to "This train has been delayed by a member of train crew being unavailable",
        109 to "This train has been delayed by a passenger being taken ill",
        110 to "This train has been delayed by a passenger having been taken ill earlier",
        111 to "This train has been delayed by a person hit by a train",
        112 to "This train has been delayed by a person hit by a train earlier",
        113 to "This train has been delayed by a problem at a level crossing",
        114 to "This train has been delayed by a problem currently under investigation",
        115 to "This train has been delayed by a problem near the railway",
        116 to "This train has been delayed by a problem with a river bridge",
        117 to "This train has been delayed by a problem with line side equipment",
        118 to "This train has been delayed by a security alert",
        119 to "This train has been delayed by a train derailed earlier",
        120 to "This train has been delayed by a train fault",
        121 to "This train has been delayed by a train late from the depot",
        122 to "This train has been delayed by a train late from the depot earlier",
        123 to "This train has been delayed by a trespass incident",
        124 to "This train has been delayed by a vehicle striking a bridge",
        125 to "This train has been delayed by a vehicle striking a bridge earlier",
        126 to "This train has been delayed by an earlier broken down train",
        128 to "This train has been delayed by an earlier landslip",
        129 to "This train has been delayed by an earlier line-side fire",
        130 to "This train has been delayed by an earlier operating incident",
        131 to "This train has been delayed by an earlier problem at a level crossing",
        132 to "This train has been delayed by an earlier problem near the railway",
        133 to "This train has been delayed by an earlier problem with a river bridge",
        134 to "This train has been delayed by an earlier problem with line side equipment",
        135 to "This train has been delayed by an earlier security alert",
        136 to "This train has been delayed by an earlier train fault",
        137 to "This train has been delayed by an earlier trespass incident",
        138 to "This train has been delayed by an obstruction on the line",
        139 to "This train has been delayed by an obstruction on the line earlier",
        140 to "This train has been delayed by an operating incident",
        141 to "This train has been delayed by an unusually large passenger flow",
        142 to "This train has been delayed by an unusually large passenger flow earlier",
        143 to "This train has been delayed by animals on the line",
        144 to "This train has been delayed by animals on the line earlier",
        145 to "This train has been delayed by congestion caused by earlier delays",
        146 to "This train has been delayed by disruptive passengers",
        147 to "This train has been delayed by disruptive passengers earlier",
        148 to "This train has been delayed by earlier electrical supply problems",
        149 to "This train has been delayed by earlier emergency engineering works",
        150 to "This train has been delayed by earlier industrial action",
        151 to "This train has been delayed by earlier overhead wire problems",
        152 to "This train has been delayed by earlier over-running engineering works",
        153 to "This train has been delayed by earlier signalling problems",
        154 to "This train has been delayed by earlier vandalism",
        155 to "This train has been delayed by electrical supply problems",
        156 to "This train has been delayed by emergency engineering works",
        157 to "This train has been delayed by emergency services dealing with a prior incident",
        158 to "This train has been delayed by emergency services dealing with an incident",
        159 to "This train has been delayed by fire alarms sounding at a station",
        160 to "This train has been delayed by fire alarms sounding earlier at a station",
        161 to "This train has been delayed by flooding",
        162 to "This train has been delayed by flooding earlier",
        163 to "This train has been delayed by fog",
        164 to "This train has been delayed by fog earlier",
        165 to "This train has been delayed by high winds",
        166 to "This train has been delayed by high winds earlier",
        167 to "This train has been delayed by industrial action",
        168 to "This train has been delayed by lightning having damaged equipment",
        169 to "This train has been delayed by overhead wire problems",
        170 to "This train has been delayed by over-running engineering works",
        171 to "This train has been delayed by passengers transferring between trains",
        172 to "This train has been delayed by passengers transferring between trains earlier",
        173 to "This train has been delayed by poor rail conditions",
        174 to "This train has been delayed by poor rail conditions earlier",
        175 to "This train has been delayed by poor weather conditions",
        176 to "This train has been delayed by poor weather conditions earlier",
        177 to "This train has been delayed by safety checks being made",
        178 to "This train has been delayed by safety checks having been made earlier",
        179 to "This train has been delayed by signalling problems",
        180 to "This train has been delayed by snow",
        181 to "This train has been delayed by snow earlier",
        182 to "This train has been delayed by speed restrictions having been imposed",
        183 to "This train has been delayed by train crew having been unavailable earlier",
        184 to "This train has been delayed by vandalism",
        185 to "This train has been delayed by waiting earlier for a train crew member",
        186 to "This train has been delayed by waiting for a train crew member",
        187 to "This train has been delayed by engineering works",
        501 to "This train has been delayed by a broken down train",
        502 to "This train has been delayed by a broken windscreen on the train",
        503 to "This train has been delayed by a shortage of trains because of accident damage",
        504 to "This train has been delayed by a shortage of trains because of extra safety inspections",
        505 to "This train has been delayed by a shortage of trains because of vandalism",
        506 to "This train has been delayed by a shortage of trains following damage by snow and ice",
        507 to "This train has been delayed by more trains than usual needing repairs at the same time",
        508 to "This train has been delayed by the train for this service having broken down",
        509 to "This train has been delayed by this train breaking down",
        510 to "This train has been delayed by a collision between trains",
        511 to "This train has been delayed by a collision with the buffers at a station",
        512 to "This train has been delayed by a derailed train",
        513 to "This train has been delayed by a derailment within the depot",
        514 to "This train has been delayed by a low speed derailment",
        515 to "This train has been delayed by a train being involved in an accident",
        516 to "This train has been delayed by trains being involved in an accident",
        517 to "This train has been delayed by a fire at a station",
        518 to "This train has been delayed by a fire at a station earlier today",
        519 to "This train has been delayed by a landslip",
        520 to "This train has been delayed by a fire next to the track",
        521 to "This train has been delayed by a fire on a train",
        522 to "This train has been delayed by a member of on train staff being taken ill",
        523 to "This train has been delayed by a shortage of on train staff",
        524 to "This train has been delayed by a shortage of train conductors",
        525 to "This train has been delayed by a shortage of train crew",
        526 to "This train has been delayed by a shortage of train drivers",
        527 to "This train has been delayed by a shortage of train guards",
        528 to "This train has been delayed by a shortage of train managers",
        529 to "This train has been delayed by severe weather preventing train crew getting to work",
        530 to "This train has been delayed by the train conductor being taken ill",
        531 to "This train has been delayed by the train driver being taken ill",
        532 to "This train has been delayed by the train guard being taken ill",
        533 to "This train has been delayed by the train manager being taken ill",
        534 to "This train has been delayed by a passenger being taken ill at a station",
        535 to "This train has been delayed by a passenger being taken ill on a train",
        536 to "This train has been delayed by a passenger being taken ill on this train",
        537 to "This train has been delayed by a passenger being taken ill at a station earlier today",
        538 to "This train has been delayed by a passenger being taken ill on a train earlier today",
        539 to "This train has been delayed by a passenger being taken ill on this train earlier in its journey",
        540 to "This train has been delayed by a person being hit by a train",
        541 to "This train has been delayed by a person being hit by a train earlier today",
        542 to "This train has been delayed by a collision at a level crossing",
        543 to "This train has been delayed by a fault with barriers at a level crossing",
        544 to "This train has been delayed by a road accident at a level crossing",
        545 to "This train has been delayed by a road vehicle colliding with level crossing barriers",
        546 to "This train has been delayed by a road vehicle damaging track at a level crossing",
        547 to "This train has been delayed by a problem currently under investigation",
        548 to "This train has been delayed by a burst water main near the railway",
        549 to "This train has been delayed by a chemical spillage near the railway",
        550 to "This train has been delayed by a fire near the railway involving gas cylinders",
        551 to "This train has been delayed by a fire near the railway suspected to involve gas cylinders",
        552 to "This train has been delayed by a fire on property near the railway",
        553 to "This train has been delayed by a gas leak near the railway",
        554 to "This train has been delayed by a road accident near the railway",
        555 to "This train has been delayed by a wartime bomb near the railway",
        556 to "This train has been delayed by ambulance service dealing with an incident near the railway",
        557 to "This train has been delayed by emergency services dealing with an incident near the railway",
        558 to "This train has been delayed by fire brigade dealing with an incident near the railway",
        559 to "This train has been delayed by police dealing with an incident near the railway",
        560 to "This train has been delayed by a boat colliding with a bridge",
        561 to "This train has been delayed by a fault with a swing bridge over a river",
        562 to "This train has been delayed by a problem with a river bridge",
        563 to "This train has been delayed by a problem with line-side equipment",
        564 to "This train has been delayed by a security alert at a station",
        565 to "This train has been delayed by a security alert on another train",
        566 to "This train has been delayed by a security alert on this train",
        567 to "This train has been delayed by a train derailment earlier today",
        568 to "This train has been delayed by a train derailment yesterday",
        569 to "This train has been delayed by a fault occurring when attaching a part of a train",
        570 to "This train has been delayed by a fault occurring when attaching a part of this train",
        571 to "This train has been delayed by a fault occurring when detaching a part of a train",
        572 to "This train has been delayed by a fault occurring when detaching a part of this train",
        573 to "This train has been delayed by a fault on a train in front of this one",
        574 to "This train has been delayed by a fault on this train",
        575 to "This train has been delayed by this train being late from the depot",
        576 to "This train has been delayed by trespassers on the railway",
        577 to "This train has been delayed by a bus colliding with a bridge",
        578 to "This train has been delayed by a lorry colliding with a bridge",
        579 to "This train has been delayed by a road vehicle colliding with a bridge",
        580 to "This train has been delayed by a bus colliding with a bridge earlier on this train's journey",
        581 to "This train has been delayed by a bus colliding with a bridge earlier today",
        582 to "This train has been delayed by a lorry colliding with a bridge earlier on this train's journey",
        583 to "This train has been delayed by a lorry colliding with a bridge earlier today",
        584 to "This train has been delayed by a road vehicle colliding with a bridge earlier on this train's journey",
        585 to "This train has been delayed by a road vehicle colliding with a bridge earlier today",
        586 to "This train has been delayed by a broken down train earlier today",
        587 to "This train has been delayed by an earlier landslip",
        588 to "This train has been delayed by a fire next to the track earlier today",
        589 to "This train has been delayed by a fire on a train earlier today",
        590 to "This train has been delayed by a coach becoming uncoupled on a train earlier in its journey",
        591 to "This train has been delayed by a coach becoming uncoupled on a train earlier today",
        592 to "This train has been delayed by a coach becoming uncoupled on this train earlier in its journey",
        593 to "This train has been delayed by a coach becoming uncoupled on this train earlier today",
        594 to "This train has been delayed by a train not stopping at a station it was supposed to earlier in its journey",
        595 to "This train has been delayed by a train not stopping at a station it was supposed to earlier today",
        596 to "This train has been delayed by a train not stopping in the correct position at a station earlier in its journey",
        597 to "This train has been delayed by a train not stopping in the correct position at a station earlier today",
        598 to "This train has been delayed by a train's automatic braking system being activated earlier in its journey",
        599 to "This train has been delayed by a train's automatic braking system being activated earlier today",
        600 to "This train has been delayed by an operational incident earlier in its journey",
        601 to "This train has been delayed by an operational incident earlier today",
        602 to "This train has been delayed by this train not stopping at a station it was supposed to earlier in its journey",
        603 to "This train has been delayed by this train not stopping at a station it was supposed to earlier today",
        604 to "This train has been delayed by this train not stopping in the correct position at a station earlier in its journey",
        605 to "This train has been delayed by this train not stopping in the correct position at a station earlier today",
        606 to "This train has been delayed by this train's automatic braking system being activated earlier in its journey",
        607 to "This train has been delayed by this train's automatic braking system being activated earlier today",
        608 to "This train has been delayed by a collision at a level crossing earlier today",
        609 to "This train has been delayed by a collision at a level crossing yesterday",
        610 to "This train has been delayed by a fault with barriers at a level crossing earlier today",
        611 to "This train has been delayed by a fault with barriers at a level crossing yesterday",
        612 to "This train has been delayed by a road accident at a level crossing earlier today",
        613 to "This train has been delayed by a road accident at a level crossing yesterday",
        614 to "This train has been delayed by a road vehicle colliding with level crossing barriers earlier today",
        615 to "This train has been delayed by a road vehicle colliding with level crossing barriers yesterday",
        616 to "This train has been delayed by a road vehicle damaging track at a level crossing earlier today",
        617 to "This train has been delayed by a road vehicle damaging track at a level crossing yesterday",
        618 to "This train has been delayed by a burst water main near the railway earlier today",
        619 to "This train has been delayed by a burst water main near the railway yesterday",
        620 to "This train has been delayed by a chemical spillage near the railway earlier today",
        621 to "This train has been delayed by a chemical spillage near the railway yesterday",
        622 to "This train has been delayed by a fire near the railway involving gas cylinders earlier today",
        623 to "This train has been delayed by a fire near the railway involving gas cylinders yesterday",
        624 to "This train has been delayed by a fire near the railway suspected to involve gas cylinders earlier today",
        625 to "This train has been delayed by a fire near the railway suspected to involve gas cylinders yesterday",
        626 to "This train has been delayed by a fire on property near the railway earlier today",
        627 to "This train has been delayed by a fire on property near the railway yesterday",
        628 to "This train has been delayed by a gas leak near the railway earlier today",
        629 to "This train has been delayed by a gas leak near the railway yesterday",
        630 to "This train has been delayed by a road accident near the railway earlier today",
        631 to "This train has been delayed by a road accident near the railway yesterday",
        632 to "This train has been delayed by a wartime bomb near the railway earlier today",
        633 to "This train has been delayed by a wartime bomb near the railway yesterday",
        634 to "This train has been delayed by a wartime bomb which has now been made safe",
        635 to "This train has been delayed by ambulance service dealing with an incident near the railway earlier today",
        636 to "This train has been delayed by ambulance service dealing with an incident near the railway yesterday",
        637 to "This train has been delayed by emergency services dealing with an incident near the railway earlier today",
        638 to "This train has been delayed by emergency services dealing with an incident near the railway yesterday",
        639 to "This train has been delayed by fire brigade dealing with an incident near the railway earlier today",
        640 to "This train has been delayed by fire brigade dealing with an incident near the railway yesterday",
        641 to "This train has been delayed by police dealing with an incident near the railway earlier today",
        642 to "This train has been delayed by police dealing with an incident near the railway yesterday",
        643 to "This train has been delayed by a boat colliding with a bridge earlier today",
        644 to "This train has been delayed by a fault with a swing bridge over a river earlier today",
        645 to "This train has been delayed by a problem with a river bridge earlier today",
        646 to "This train has been delayed by an earlier problem with line-side equipment",
        647 to "This train has been delayed by a security alert earlier today",
        648 to "This train has been delayed by a fault on this train which is now fixed",
        649 to "This train has been delayed by trespassers on the railway earlier in this train's journey",
        650 to "This train has been delayed by trespassers on the railway earlier today",
        651 to "This train has been delayed by a bicycle on the track",
        652 to "This train has been delayed by a road vehicle blocking the railway",
        653 to "This train has been delayed by a supermarket trolley on the track",
        654 to "This train has been delayed by a train hitting an obstruction on the line",
        655 to "This train has been delayed by a tree blocking the railway",
        656 to "This train has been delayed by an obstruction on the track",
        657 to "This train has been delayed by checking reports of an obstruction on the line",
        658 to "This train has been delayed by this train hitting an obstruction on the line",
        659 to "This train has been delayed by a bicycle on the track earlier on this train's journey",
        660 to "This train has been delayed by a bicycle on the track earlier today",
        661 to "This train has been delayed by a road vehicle blocking the railway earlier on this train's journey",
        662 to "This train has been delayed by a road vehicle blocking the railway earlier today",
        663 to "This train has been delayed by a supermarket trolley on the track earlier on this train's journey",
        664 to "This train has been delayed by a supermarket trolley on the track earlier today",
        665 to "This train has been delayed by a train hitting an obstruction on the line earlier on this train's journey",
        666 to "This train has been delayed by a train hitting an obstruction on the line earlier today",
        667 to "This train has been delayed by a tree blocking the railway earlier on this train's journey",
        668 to "This train has been delayed by a tree blocking the railway earlier today",
        669 to "This train has been delayed by an obstruction on the track earlier on this train's journey",
        670 to "This train has been delayed by an obstruction on the track earlier today",
        671 to "This train has been delayed by checking reports of an obstruction on the line earlier on this train's journey",
        672 to "This train has been delayed by checking reports of an obstruction on the line earlier today",
        673 to "This train has been delayed by this train hitting an obstruction on the line earlier in its journey",
        674 to "This train has been delayed by this train hitting an obstruction on the line earlier on this train's journey",
        675 to "This train has been delayed by this train hitting an obstruction on the line earlier today",
        676 to "This train has been delayed by a coach becoming uncoupled on a train",
        677 to "This train has been delayed by a coach becoming uncoupled on this train",
        678 to "This train has been delayed by a train not stopping at a station it was supposed to",
        679 to "This train has been delayed by a train not stopping in the correct position at a station",
        680 to "This train has been delayed by a train's automatic braking system being activated",
        681 to "This train has been delayed by an operational incident",
        682 to "This train has been delayed by this train not stopping at a station it was supposed to",
        683 to "This train has been delayed by this train not stopping in the correct position at a station",
        684 to "This train has been delayed by this train's automatic braking system being activated",
        685 to "This train has been delayed by overcrowding",
        686 to "This train has been delayed by overcrowding as this train has fewer coaches than normal",
        687 to "This train has been delayed by overcrowding because an earlier train had fewer coaches than normal",
        688 to "This train has been delayed by overcrowding because of a concert",
        689 to "This train has been delayed by overcrowding because of a football match",
        690 to "This train has been delayed by overcrowding because of a marathon",
        691 to "This train has been delayed by overcrowding because of a rugby match",
        692 to "This train has been delayed by overcrowding because of a sporting event",
        693 to "This train has been delayed by overcrowding because of an earlier cancellation",
        694 to "This train has been delayed by overcrowding because of an event",
        695 to "This train has been delayed by overcrowding earlier on this train's journey",
        696 to "This train has been delayed by animals on the railway",
        697 to "This train has been delayed by cattle on the railway",
        698 to "This train has been delayed by horses on the railway",
        699 to "This train has been delayed by sheep on the railway",
        700 to "This train has been delayed by animals on the railway earlier today",
        701 to "This train has been delayed by cattle on the railway earlier today",
        702 to "This train has been delayed by horses on the railway earlier today",
        703 to "This train has been delayed by sheep on the railway earlier today",
        704 to "This train has been delayed by passengers causing a disturbance on a train",
        705 to "This train has been delayed by passengers causing a disturbance on this train",
        706 to "This train has been delayed by passengers causing a disturbance earlier in this train's journey",
        707 to "This train has been delayed by passengers causing a disturbance on a train earlier today",
        708 to "This train has been delayed by a fault with the electric third rail earlier on this train's journey",
        709 to "This train has been delayed by a fault with the electric third rail earlier today",
        710 to "This train has been delayed by damage to the electric third rail earlier on this train's journey",
        711 to "This train has been delayed by damage to the electric third rail earlier today",
        712 to "This train has been delayed by failure of the electricity supply earlier on this train's journey",
        713 to "This train has been delayed by failure of the electricity supply earlier today",
        714 to "This train has been delayed by the electricity being switched off for safety reasons earlier on this train's journey",
        715 to "This train has been delayed by the electricity being switched off for safety reasons earlier today",
        716 to "This train has been delayed by urgent repairs to a bridge earlier today",
        717 to "This train has been delayed by urgent repairs to a tunnel earlier today",
        718 to "This train has been delayed by urgent repairs to the railway earlier today",
        719 to "This train has been delayed by urgent repairs to the track earlier today",
        720 to "This train has been delayed by expected industrial action earlier today",
        721 to "This train has been delayed by expected industrial action yesterday",
        722 to "This train has been delayed by industrial action earlier today",
        723 to "This train has been delayed by industrial action yesterday",
        724 to "This train has been delayed by an object being caught on the overhead electric wires earlier on this train's journey",
        725 to "This train has been delayed by an object being caught on the overhead electric wires earlier today",
        726 to "This train has been delayed by damage to the overhead electric wires earlier on this train's journey",
        727 to "This train has been delayed by damage to the overhead electric wires earlier today",
        728 to "This train has been delayed by earlier engineering works not being finished on time",
        729 to "This train has been delayed by a fault with the on train signalling system earlier on this train's journey",
        730 to "This train has been delayed by a fault with the on train signalling system earlier today",
        731 to "This train has been delayed by a fault with the radio system between the driver and the signaller earlier on this train's journey",
        732 to "This train has been delayed by a fault with the radio system between the driver and the signaller earlier today",
        733 to "This train has been delayed by a fault with the signalling system earlier on this train's journey",
        734 to "This train has been delayed by a fault with the signalling system earlier today",
        735 to "This train has been delayed by signalling staff being taken ill earlier on this train's journey",
        736 to "This train has been delayed by signalling staff being taken ill earlier today",
        737 to "This train has been delayed by the fire alarm sounding in a signalbox earlier on this train's journey",
        738 to "This train has been delayed by the fire alarm sounding in a signalbox earlier today",
        739 to "This train has been delayed by the fire alarm sounding in the signalling centre earlier on this train's journey",
        740 to "This train has been delayed by the fire alarm sounding in the signalling centre earlier today",
        741 to "This train has been delayed by attempted theft of overhead line electrification equipment earlier today",
        742 to "This train has been delayed by attempted theft of overhead line electrification equipment yesterday",
        743 to "This train has been delayed by attempted theft of railway equipment earlier today",
        744 to "This train has been delayed by attempted theft of railway equipment yesterday",
        745 to "This train has been delayed by attempted theft of signalling cables earlier today",
        746 to "This train has been delayed by attempted theft of signalling cables yesterday",
        747 to "This train has been delayed by attempted theft of third rail electrification equipment earlier today",
        748 to "This train has been delayed by attempted theft of third rail electrification equipment yesterday",
        749 to "This train has been delayed by theft of overhead line electrification equipment earlier today",
        750 to "This train has been delayed by theft of overhead line electrification equipment yesterday",
        751 to "This train has been delayed by theft of railway equipment earlier today",
        752 to "This train has been delayed by theft of railway equipment yesterday",
        753 to "This train has been delayed by theft of signalling cables earlier today",
        754 to "This train has been delayed by theft of signalling cables yesterday",
        755 to "This train has been delayed by theft of third rail electrification equipment earlier today",
        756 to "This train has been delayed by theft of third rail electrification equipment yesterday",
        757 to "This train has been delayed by vandalism at a station earlier today",
        758 to "This train has been delayed by vandalism at a station yesterday",
        759 to "This train has been delayed by vandalism of railway equipment earlier today",
        760 to "This train has been delayed by vandalism of railway equipment yesterday",
        761 to "This train has been delayed by vandalism on a train earlier today",
        762 to "This train has been delayed by vandalism on a train yesterday",
        763 to "This train has been delayed by vandalism on this train earlier today",
        764 to "This train has been delayed by vandalism on this train yesterday",
        765 to "This train has been delayed by a fault with the electric third rail",
        766 to "This train has been delayed by damage to the electric third rail",
        767 to "This train has been delayed by failure of the electricity supply",
        768 to "This train has been delayed by the electricity being switched off for safety reasons",
        769 to "This train has been delayed by urgent repairs to a bridge",
        770 to "This train has been delayed by urgent repairs to a tunnel",
        771 to "This train has been delayed by urgent repairs to the railway",
        772 to "This train has been delayed by urgent repairs to the track",
        773 to "This train has been delayed by the emergency services dealing with an incident earlier today",
        774 to "This train has been delayed by ambulance service dealing with an incident",
        775 to "This train has been delayed by fire brigade dealing with an incident",
        776 to "This train has been delayed by police dealing with an incident",
        777 to "This train has been delayed by the emergency services dealing with an incident",
        778 to "This train has been delayed by the fire alarm sounding at a station",
        779 to "This train has been delayed by the fire alarm sounding at a station earlier today",
        780 to "This train has been delayed by a burst water main flooding the railway",
        781 to "This train has been delayed by a river flooding the railway",
        782 to "This train has been delayed by flood water making the railway potentially unsafe",
        783 to "This train has been delayed by flooding",
        784 to "This train has been delayed by heavy rain flooding the railway",
        785 to "This train has been delayed by predicted flooding",
        786 to "This train has been delayed by the sea flooding the railway",
        787 to "This train has been delayed by a burst water main flooding the railway earlier today",
        788 to "This train has been delayed by a river flooding the railway earlier today",
        789 to "This train has been delayed by flood water making the railway potentially unsafe earlier today",
        790 to "This train has been delayed by flooding earlier in this train's journey",
        791 to "This train has been delayed by flooding earlier today",
        792 to "This train has been delayed by heavy rain flooding the railway earlier today",
        793 to "This train has been delayed by predicted flooding earlier today",
        794 to "This train has been delayed by the sea flooding the railway earlier today",
        795 to "This train has been delayed by thick fog",
        796 to "This train has been delayed by thick fog earlier in this train's journey",
        797 to "This train has been delayed by thick fog earlier today",
        798 to "This train has been delayed by forecasted high winds",
        799 to "This train has been delayed by high winds",
        800 to "This train has been delayed by high winds earlier in this train's journey",
        801 to "This train has been delayed by high winds earlier today",
        802 to "This train has been delayed by expected industrial action",
        803 to "This train has been delayed by industrial action",
        804 to "This train has been delayed by lightning damaging a station",
        805 to "This train has been delayed by lightning damaging a train",
        806 to "This train has been delayed by lightning damaging equipment",
        807 to "This train has been delayed by lightning damaging the electricity supply",
        808 to "This train has been delayed by lightning damaging the signalling system",
        809 to "This train has been delayed by lightning damaging this train",
        810 to "This train has been delayed by an object being caught on the overhead electric wires",
        811 to "This train has been delayed by damage to the overhead electric wires",
        812 to "This train has been delayed by engineering works not being finished on time",
        813 to "This train has been delayed by forecasted slippery rails",
        814 to "This train has been delayed by ice preventing this train getting electricity from the third rail",
        815 to "This train has been delayed by ice preventing trains getting electricity from the third rail",
        816 to "This train has been delayed by slippery rails",
        817 to "This train has been delayed by slippery rails earlier in this train's journey",
        818 to "This train has been delayed by slippery rails earlier today",
        819 to "This train has been delayed by forecasted severe weather",
        820 to "This train has been delayed by severe weather",
        821 to "This train has been delayed by severe weather earlier",
        822 to "This train has been delayed by severe weather earlier in this train's journey",
        823 to "This train has been delayed by severe weather earlier today",
        824 to "This train has been delayed by a safety inspection of the track",
        825 to "This train has been delayed by a safety inspection on a train",
        826 to "This train has been delayed by a safety inspection on this train",
        827 to "This train has been delayed by a safety inspection of the track earlier today",
        828 to "This train has been delayed by a safety inspection on a train earlier today",
        829 to "This train has been delayed by a safety inspection on this train earlier in its journey",
        830 to "This train has been delayed by a fault with the on train signalling system",
        831 to "This train has been delayed by a fault with the radio system between the driver and the signaller",
        832 to "This train has been delayed by a fault with the signalling system",
        833 to "This train has been delayed by signalling staff being taken ill",
        834 to "This train has been delayed by the fire alarm sounding in a signalbox",
        835 to "This train has been delayed by the fire alarm sounding in the signalling centre",
        836 to "This train has been delayed by forecasted heavy snow",
        837 to "This train has been delayed by heavy snow",
        838 to "This train has been delayed by heavy snow earlier in this train's journey",
        839 to "This train has been delayed by heavy snow earlier today",
        840 to "This train has been delayed by heavy snow over recent days",
        841 to "This train has been delayed by a speed restriction",
        842 to "This train has been delayed by a speed restriction because of fog",
        843 to "This train has been delayed by a speed restriction because of fog earlier on this train's journey",
        844 to "This train has been delayed by a speed restriction because of fog earlier today",
        845 to "This train has been delayed by a speed restriction because of heavy rain",
        846 to "This train has been delayed by a speed restriction because of heavy rain earlier on this train's journey",
        847 to "This train has been delayed by a speed restriction because of heavy rain earlier today",
        848 to "This train has been delayed by a speed restriction because of high track temperatures",
        849 to "This train has been delayed by a speed restriction because of high track temperatures earlier on this train's journey",
        850 to "This train has been delayed by a speed restriction because of high track temperatures earlier today",
        851 to "This train has been delayed by a speed restriction because of high winds",
        852 to "This train has been delayed by a speed restriction because of high winds earlier on this train's journey",
        853 to "This train has been delayed by a speed restriction because of high winds earlier today",
        854 to "This train has been delayed by a speed restriction because of severe weather",
        855 to "This train has been delayed by a speed restriction because of severe weather earlier on this train's journey",
        856 to "This train has been delayed by a speed restriction because of severe weather earlier today",
        857 to "This train has been delayed by a speed restriction because of snow and ice",
        858 to "This train has been delayed by a speed restriction because of snow and ice earlier on this train's journey",
        859 to "This train has been delayed by a speed restriction because of snow and ice earlier today",
        860 to "This train has been delayed by a speed restriction earlier on this train's journey",
        861 to "This train has been delayed by a speed restriction earlier today",
        862 to "This train has been delayed by a speed restriction in a tunnel",
        863 to "This train has been delayed by a speed restriction in a tunnel earlier on this train's journey",
        864 to "This train has been delayed by a speed restriction in a tunnel earlier today",
        865 to "This train has been delayed by a speed restriction over a bridge",
        866 to "This train has been delayed by a speed restriction over a bridge earlier on this train's journey",
        867 to "This train has been delayed by a speed restriction over a bridge earlier today",
        868 to "This train has been delayed by a speed restriction over an embankment",
        869 to "This train has been delayed by a speed restriction over an embankment earlier on this train's journey",
        870 to "This train has been delayed by a speed restriction over an embankment earlier today",
        871 to "This train has been delayed by a speed restriction over defective track",
        872 to "This train has been delayed by a speed restriction over defective track earlier on this train's journey",
        873 to "This train has been delayed by a speed restriction over defective track earlier today",
        874 to "This train has been delayed by attempted theft of overhead line electrification equipment",
        875 to "This train has been delayed by attempted theft of railway equipment",
        876 to "This train has been delayed by attempted theft of signalling cables",
        877 to "This train has been delayed by attempted theft of third rail electrification equipment",
        878 to "This train has been delayed by theft of overhead line electrification equipment",
        879 to "This train has been delayed by theft of railway equipment",
        880 to "This train has been delayed by theft of signalling cables",
        881 to "This train has been delayed by theft of third rail electrification equipment",
        882 to "This train has been delayed by vandalism at a station",
        883 to "This train has been delayed by vandalism of railway equipment",
        884 to "This train has been delayed by vandalism on a train",
        885 to "This train has been delayed by vandalism on this train",
        886 to "This train has been delayed by train crew being delayed",
        887 to "This train has been delayed by train crew being delayed by service disruption",
        888 to "This train has been delayed by a bridge being damaged",
        889 to "This train has been delayed by a bridge being damaged by a boat",
        890 to "This train has been delayed by a bridge being damaged by a road vehicle",
        891 to "This train has been delayed by a bridge having collapsed",
        892 to "This train has been delayed by a broken rail",
        893 to "This train has been delayed by a late departure while the train was cleaned specially",
        894 to "This train has been delayed by a late running freight train",
        895 to "This train has been delayed by a late running train being in front of this one",
        896 to "This train has been delayed by a points failure",
        897 to "This train has been delayed by a power cut at the station",
        898 to "This train has been delayed by a problem with the station lighting",
        899 to "This train has been delayed by a rail buckling in the heat",
        900 to "This train has been delayed by a railway embankment being damaged",
        901 to "This train has been delayed by a shortage of station staff",
        902 to "This train has been delayed by a tunnel being closed for safety reasons",
        903 to "This train has been delayed by an incident at the airport",
        904 to "This train has been delayed by congestion",
        905 to "This train has been delayed by the communication alarm being activated on a train",
        906 to "This train has been delayed by the communication alarm being activated on this train",
        907 to "This train has been delayed by the train departing late to maintain customer connections",
        908 to "This train has been delayed by the train making extra stops because a train was cancelled",
        909 to "This train has been delayed by the train making extra stops because of service disruption",
        910 to "This train has been delayed by waiting for a part of the train to be attached",
        911 to "This train has been delayed by a fault on a train",
        912 to "This train has been delayed by a problem with platform equipment",
        913 to "This train has been delayed by a fault on a train earlier",
        914 to "This train has been delayed by issues with communication systems",
        915 to "This train has been delayed by a problem in the depot",
        916 to "This train has been delayed by signalling staff being unavailable",
        917 to "This train has been delayed by staff training",
        918 to "This train has been delayed by a short-notice change to the timetable",
        919 to "This train has been delayed by misuse of a level crossing",
        920 to "This train has been delayed by a member of train crew being unavailable",
        921 to "This train has been delayed by a member of train crew being unavailable earlier"
    )
}
