package com.traintracker

/**
 * Network Rail TRUST cancellation and delay reason codes.
 * Source: Network Rail Delay Attribution Guide (via Open Rail Data Wiki).
 *
 * These two-letter alpha codes appear in TRUST Train Cancellation messages
 * as the canx_reason_code field.
 *
 * Use [resolveCancel] to get a human-readable cancellation reason.
 */
object ReasonCodes {

    fun resolveCancel(raw: String): String {
        if (raw.isBlank()) return ""
        return cancelReasons[raw.trim().uppercase()] ?: "Cancellation ($raw)"
    }

    // ── TRUST cancellation reason codes ──────────────────────────────────────
    // Grouped as per the Delay Attribution Guide

    private val cancelReasons: Map<String, String> = mapOf(

        // A* — Freight Terminal Operations
        "AA" to "Waiting acceptance into terminal or yard",
        "AC" to "Waiting train preparation",
        "AD" to "Terminal staff shortage",
        "AE" to "Congestion in terminal or yard",
        "AG" to "Wagon load incident",
        "AH" to "Customer equipment breakdown",
        "AJ" to "Waiting customer's traffic",
        "AK" to "Safety incident in freight yard",
        "AX" to "Off-network infrastructure failure",
        "AZ" to "Other freight terminal cause",

        // D* — Holding Codes
        "DA" to "Non-technical fleet holding",
        "DB" to "Train operations holding",
        "DC" to "Train crew holding",
        "DD" to "Technical fleet holding",
        "DE" to "Station holding",
        "DF" to "External causes holding",
        "DG" to "Freight terminal holding",
        "DH" to "Adhesion/autumn holding",

        // F* — Freight Operating
        "FA" to "Dangerous goods incident",
        "FC" to "Freight driver error or SPAD",
        "FE" to "Train crew not available",
        "FF" to "Freight diagramming issue",
        "FG" to "Driver adhering to professional driving standards",
        "FH" to "Freight planning issue",
        "FJ" to "Freight control decision",
        "FK" to "Train diverted at freight operator request",
        "FL" to "Train cancelled at freight operator request",
        "FM" to "Lamp out or incorrectly shown",
        "FO" to "Time lost — operator cause under investigation",
        "FW" to "Late start not explained by operator",
        "FX" to "Train running at lower speed than planned",
        "FZ" to "Other freight operator cause",

        // I* — Infrastructure
        "IA" to "Signal failure",
        "IB" to "Points failure",
        "IC" to "Track circuit failure",
        "ID" to "Level crossing fault",
        "IE" to "Signalling power supply failure",
        "IF" to "Train describer or panel failure",
        "IG" to "Block failure",
        "IH" to "Power supply and distribution failure",
        "II" to "Signalling cable fault",
        "IJ" to "AWS/ATP/TPWS failure",
        "IK" to "Telecom equipment failure",
        "IL" to "Token equipment failure",
        "IM" to "Infrastructure balise failure",
        "IN" to "HABD or wheel detection fault",
        "IP" to "Points failure — heaters fitted but not working",
        "IQ" to "Trackside sign defect",
        "IR" to "Broken or buckled rail",
        "IS" to "Track defect",
        "IT" to "Rough ride — cause unknown",
        "IV" to "Earthslip or rock fall",
        "IW" to "Snow or ice affecting infrastructure",
        "I1" to "Overhead line or third rail defect",
        "I2" to "AC/DC trip",
        "I4" to "Power supply failure or reduction",
        "I5" to "Possession over-run",
        "I6" to "Line block or track patrol",
        "I7" to "Engineer's train late or failed",
        "I8" to "Animal strike or incursion",
        "I9" to "Fire on infrastructure",

        // J* — Infrastructure (other)
        "JA" to "Speed restriction for track work",
        "JB" to "Reactionary delay to TSR",
        "JD" to "Structures defect — bridge or tunnel",
        "JF" to "Off-track asset defect",
        "JG" to "ESR/TSR due to cancelled possession",
        "JH" to "Critical rail temperature speed restriction",
        "JK" to "Flooding",
        "JL" to "Safety incident — maintenance staff error",
        "JP" to "Vegetation maintenance failure",
        "JS" to "Track condition speed restriction",
        "JT" to "Points failure — no heaters fitted",
        "JX" to "Miscellaneous obstruction on track",
        "J2" to "Train dispatch equipment failure",
        "J3" to "Axle counter failure",
        "J6" to "Lightning strike on unprotected assets",
        "J7" to "ETCS/ERTMS equipment failure",
        "J9" to "Preventative maintenance — remote condition monitoring",

        // M* — Mechanical/Fleet
        "MB" to "Electric locomotive failure",
        "MC" to "Diesel locomotive failure",
        "MD" to "Technical failure below solebar",
        "ME" to "Steam locomotive failure",
        "ML" to "Wagon, coach or parcel vehicle fault",
        "MN" to "Brake or wheel flat fault",
        "MP" to "Rail/wheel adhesion problem",
        "MR" to "Sanders or scrubber fault",
        "MS" to "Planned underpowered or short-formed service",
        "MT" to "Train-borne safety system fault",
        "MU" to "Depot operating problem",
        "MV" to "Engineer's on-track equipment failure",
        "MW" to "Weather affecting rolling stock",
        "MY" to "Coupler or coupler system fault",
        "M1" to "Pantograph or shoe beam fault",
        "M2" to "ATO/ETCS equipment delay",
        "M7" to "Door or door system fault",
        "M8" to "Technical failure above solebar",
        "M9" to "Fleet equipment defect — no fault found",
        "M0" to "Cab-based safety system fault",

        // O* — Network Rail Operating
        "OA" to "Regulation decision",
        "OB" to "Signaller not applying regulation policy",
        "OC" to "Signaller error or mis-routing",
        "OD" to "Network Rail control decision",
        "OG" to "Ice on conductor rail or OHLE",
        "OH" to "ARS/TMS software problem",
        "OJ" to "Fire at station affecting other operators",
        "OK" to "Operating staff oversight or absence",
        "OL" to "Signal box not open during booked hours",
        "ON" to "Delays not properly investigated by Network Rail",
        "OR" to "Local box instructions",
        "OV" to "Fire or evacuation of Network Rail buildings",
        "OZ" to "Other Network Rail operating cause",

        // P* — Planned/Excluded
        "PA" to "Planned engineering works — within allowance",
        "PB" to "Published TSR — asset condition",
        "PD" to "System-generated planned cancellation",
        "PF" to "Planned engineering — diversion not in schedule",
        "PG" to "Planned cancellation — agreed day before",
        "PJ" to "Cancellation of duplicate or erroneous schedule",
        "PL" to "Commercially agreed exclusion",
        "PN" to "VSTP service delay",
        "PT" to "Authorised TRUST reporting anomaly",

        // Q* — Network Rail Non-Operating
        "QA" to "WTT schedule or LTP process issue",
        "QB" to "Planned engineering — diversion not timetabled",
        "QH" to "Adhesion problems — leaf contamination",
        "QI" to "Cautioning — railhead leaf contamination",
        "QJ" to "Special working — leaf-fall track circuit",
        "QM" to "Train schedule VAR/STP process issue",
        "QN" to "VSTP schedule or process issue",
        "QP" to "Reactionary delay to planned possession",
        "QT" to "Delay accepted under commercial agreement",

        // R* — Station Operating
        "RB" to "Passengers joining or alighting",
        "RC" to "Pre-booked assistance — reduced mobility",
        "RD" to "Attaching, detaching or shunting",
        "RE" to "Lift or escalator defect",
        "RH" to "Station evacuated — fire alarm",
        "RI" to "Waiting connections — not authorised",
        "RJ" to "Special stop orders — not authorised",
        "RK" to "Waiting connections — authorised but outside policy",
        "RL" to "Special stop orders — authorised",
        "RM" to "Waiting connections from other transport modes",
        "RO" to "Passenger taken ill on platform",
        "RP" to "Passenger dropped object whilst boarding",
        "RQ" to "Unbooked reduced mobility assistance",
        "RR" to "Loading reserved bicycles",
        "RS" to "Loading unreserved bicycles",
        "RT" to "Loading excessive luggage",
        "RU" to "Locating lost luggage",
        "RV" to "Customer information system failure",
        "RW" to "Station flooding",
        "RX" to "Station overcrowding — unplanned event",
        "RY" to "Station operating mishap",
        "RZ" to "Other station operating cause",
        "R1" to "Incorrect train dispatch by station staff",
        "R2" to "Late TRTS given by station staff",
        "R3" to "Station staff unavailable",
        "R4" to "Station staff split responsibility",
        "R5" to "Station staff error",
        "R7" to "Station overcrowding — planned event",
        "R8" to "Station delay — operator cause under investigation",

        // T* — Passenger Train Operating
        "TA" to "Train crew, stock or unit diagram issue",
        "TB" to "Train cancelled at operator's request",
        "TF" to "Seat reservation problem",
        "TG" to "Driver unavailable",
        "TH" to "Conductor or train manager unavailable",
        "TI" to "Train crew rostering problem",
        "TJ" to "Tail lamp or headlamp missing or not lit",
        "TK" to "Train catering staff issue",
        "TM" to "Connection authorised — outside policy",
        "TN" to "Late presentation from the continent",
        "TO" to "Time lost — operator cause under investigation",
        "TP" to "Special stop orders",
        "TR" to "Train operating company directive",
        "TW" to "Driver adhering to professional driving standards",
        "TX" to "Delays on non-Network Rail lines",
        "TY" to "Train operating company mishap",
        "TZ" to "Other passenger train operating cause",
        "T2" to "Delay at unstaffed station — non-DOO train",
        "T3" to "Waiting connections from other transport modes",
        "T4" to "Loading supplies including catering",
        "T8" to "Station delay — operator cause under investigation",

        // V* — External — TOC Responsibility
        "VA" to "Disorder, drunks or trespass",
        "VB" to "Vandalism or theft",
        "VC" to "Fatality or injury — struck by train",
        "VD" to "Passenger taken ill on train",
        "VE" to "Ticket irregularities",
        "VF" to "Fire caused by vandalism",
        "VG" to "Police searching train",
        "VH" to "Passenger alarm or emergency door egress activated",
        "VI" to "Security alert at station or depot",
        "VR" to "Driver adhering to standards in severe weather",
        "VW" to "Severe weather affecting passenger fleet",
        "VX" to "External events on LUL or other non-NR lines",
        "VZ" to "Other passenger or external cause",
        "V8" to "Train struck by bird",

        // X* — External — Network Rail
        "XA" to "Trespass",
        "XB" to "Vandalism or theft including objects on line",
        "XC" to "Fatality or injury — hit by train",
        "XD" to "Level crossing incident or misuse",
        "XF" to "Police searching the line",
        "XH" to "Severe heat affecting infrastructure",
        "XI" to "Security alert on Network Rail network",
        "XK" to "National Grid power failure",
        "XL" to "Fire external to but affecting the railway",
        "XM" to "External utility incident — gas or water mains",
        "XN" to "Road or crossing incident",
        "XO" to "External object fallen onto railway",
        "XP" to "Bridge strike",
        "XQ" to "Swing bridge open for river traffic",
        "XR" to "Cable vandalism or theft",
        "XT" to "Severe snow or ice affecting infrastructure",
        "XU" to "Sunlight obscuring signal or dispatch equipment",
        "XV" to "Fire — Network Rail buildings — vandalism",
        "XW" to "High winds affecting infrastructure",
        "X1" to "Fog or snow — special working implemented",
        "X2" to "Severe flooding beyond mitigation",
        "X3" to "Lightning strike — damage to protected systems",
        "X4" to "Blanket speed restriction or Key Route Strategy",
        "X8" to "Animal strike — not within Network Rail control",
        "X9" to "Points failure — severe snow or ice",

        // Y* — Reactionary
        "YA" to "Lost path — regulated for on-time train",
        "YB" to "Lost path — regulated for late-running train",
        "YC" to "Lost path — following on-time train",
        "YD" to "Lost path — following late-running train",
        "YE" to "Waiting path onto single line",
        "YG" to "Regulated — regulation policy",
        "YI" to "Late arrival of inward stock",
        "YJ" to "Late arrival of inward train crew",
        "YL" to "Waiting passenger connections — agreed",
        "YM" to "Special stop orders — agreed",
        "YN" to "Service recovery — train crew not available",
        "YO" to "Waiting platform or station congestion",
        "YP" to "Diversion from booked route",
        "YQ" to "Overcrowding — short formation",
        "YR" to "Tactical cancellation for service recovery",
        "YU" to "Service recovery — rolling stock not available",
        "YT" to "Reactionary delay — train leaving network",
        "YV" to "Train held back due to line-blocking incident",
        "YX" to "Overcrowding — caused by delay or cancellation",

        // Z* — Unexplained
        "ZS" to "No cause ascertainable",
        "ZU" to "No cause identified after full investigation",
        "ZW" to "Uninvestigated cancellation",
        "ZX" to "Uninvestigated late start",
        "ZY" to "Uninvestigated station overtime",
        "ZZ" to "Uninvestigated loss in running"
    )
}
